rules:
  leading-zero: 0
  no-color-keywords: 0
  no-color-literals: 0
  border-zero: 0
  mixins-before-declarations: 0
  no-ids: 0
  nesting-depth: 0
  empty-args: 0
  force-pseudo-nesting: 0
  brace-style: 0
